version: '3.8'

services:
 redis1:
  image: redis
  restart: always  
  volumes:
   - /docker/redis/7001/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7001/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7001:6379'     #服务端口
    - '17001:16379'   #集群端口
  command:
    # 开启集群模式
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量
  

 redis2:
  image: redis
  #network_mode: host
  restart: always
  volumes:
   - /docker/redis/7002/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7002/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7002:6379'     #服务端口
    - '17002:16379'   #集群端口
  command: 
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量

 redis3:
  image: redis
  #network_mode: host
  restart: always
  volumes:
   - /docker/redis/7003/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7003/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7003:6379'     #服务端口
    - '17003:16379'   #集群端口
  command: 
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量

 redis4:
  image: redis
  #network_mode: host
  restart: always
  volumes:
   - /docker/redis/7004/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7004/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7004:6379'     #服务端口
    - '17004:16379'   #集群端口
  command: 
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量

 redis5:
  image: redis
  #network_mode: host
  restart: always
  volumes:
   - /docker/redis/7005/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7005/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7005:6379'     #服务端口
    - '17005:16379'   #集群端口
  command: 
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量

 redis6:
  image: redis
  #network_mode: host
  restart: always
  volumes:
   - /docker/redis/7006/config/redis.conf:/etc/redis/redis.conf
   - /docker/redis/7006/data:/data
  environment:
   - TZ=Asia/Shanghai
   - LANG=en_US.UTF-8
  ports:
    - '7006:6379'     #服务端口
    - '17006:16379'   #集群端口
  command: 
    -- cluster-enabled yes
    -- requirepass "rollinrockz"
    -- masterauth "rollinrockz"
    -- bind 0.0.0.0
    -- protected-mode no
    -- appendonly yes
  privileged: true    #环境变量
