version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      PREFER_HOST_MODE: hostname
      # TODO 具体情况而定
      MODE: standalone
      JVM_XMS: 100m
      JVM_XMX: 100m
      JVM_XMN: 80m
      JVM_MS: 80m
      JVM_MMS: 80m
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 124.221.109.245
      # mysql 需要有一个nacos 数据库
      MYSQL_SERVICE_DB_NAME: nacos_devtest
      MYSQL_SERVICE_PORT: 3308
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      # 需要提供一个文件
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always