version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis
        privileged: true
        restart: always
        ports:
            - 6379:6379
        command:
            -- requirepass "rollinrockz"
            -- bind "0.0.0.0"
            # 默认yes，开启保护模式，限制为本地访问
            -- protected-mode "no"
        volumes:
            - /data/redis:/data
            #- /data/redis/redis.conf:/usr/local/etc/redis/redis.conf
  # 注意：运行时去掉注释，否则解析不成功