version: '3.8'
services:
    redis:
        image: redis:latest
        container_name: redis
        privileged: true
        restart: always
        ports:
            - 6379:6379
        command:
            -- requirepass "rollinrockz"
        volumes:
            - ./data:/data