version: '3.8'
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        privileged: true
        ports:
            - 2181:2181
            - 2888:2888
            - 2888:2888
        volumes:
            - ./data:/data