version: '3'
services:
    oracle:
        image: registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g
        container_name: oracle11g
        privileged: true
        environment:
            - TZ=Asia/Shanghai
        restart: always
        volumes:
            - /data/oracle/oradata:/home/oracle/app/oracle/oradata/
            - /data/oracle/helowin:/home/oracle/app/oracle/flash_recovery_area/helowin/
        ports:
            - "1521:1521"
#配置oracle11：
# 1、进入容器： docker exec -it oracle11g bash
# 2、切换到root用户：su root (密码是：helowin)
# 3、配置环境变量：
#    export ORACLE_HOME=/home/oracle/app/oracle/product/11.2.0/dbhome_2
#    export ORACLE_SID=helowin
#    export PATH=$ORACLE_HOME/bin:$PATH
# 4、加载环境变量：source /home/oracle/.bash_profile、 source /etc/profile
# 5、配置sys、system用户的账号和密码：
#       切换到oracle用户：su -oracle



#docker 安装oracle: https://blog.csdn.net/qq_38796548/article/details/108406354 << success >>

# docker run --name oracle_11g -d -p 1521:1521 registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g

#CREATE TABLESPACE TEST LOGGING DATAFILE '/home/oracle/tablespace/TEST.DBF' SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
#CREATE USER tester IDENTIFIED BY 123456 ACCOUNT UNLOCK DEFAULT TABLESPACE TEST;