version: '3.1'
services:
    mysql8:
        image: nacos/nacos-mysql:8.0.16
        container_name: mysql_build
        privileged: true
        restart: always
        ports:
            - 3308:3306
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nacos_devtest
            MYSQL_USER: nacos
            MYSQL_PASSWORD: nacos
        command:
            --lower_case_table_names=1
            --secure_file_priv=/var/lib/mysql
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --default-authentication-plugin=mysql_native_password
            --max_allowed_packet=128M
            --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
        volumes:
            - ./lib/mysql:/var/lib/mysql
            - ./log:/var/log/mysql
            - ./conf:/etc/mysql

