version: '3.1'
services:
    # 服务名（不能相同）
    mysql5:
        container_name: mysql5.7
        image: nacos/nacos-mysql:5.7
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nacos_devtest
            MYSQL_USER: nacos
            MYSQL_PASSWORD: nacos
        volumes:
            - ./mysql5.7:/var/lib/mysql
        ports:
            - "3306:3306"