version: '3.1'
services:
    mysql8:
        image: nacos/nacos-mysql:8.0.16
        container_name: mysql8
        privileged: true
        restart: always
        ports:
            - 3307:3306
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nacos_devtest
            MYSQL_USER: nacos
            MYSQL_PASSWORD: nacos
        command:
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --default-authentication-plugin=mysql_native_password
            --max_allowed_packet=128M
            --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
        volumes:
        # 注意 ：启动之前，mysql8 文件里面要为空
            - ./mysql8:/var/lib/mysql

